name: Run tests

on: pull_request

jobs:

  run-tests:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      shell: bash
      run: |
        go test -race -covermode=atomic ./...
